# Generated by Django 5.0 on 2024-02-15 07:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('elitpowertool', '0001_initial'),
        ('mosfet', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='circuitparamacdc',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='circuitparamacdc',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='circuitparamflybackforword',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='circuitparamflybackforword',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='circuitparamboost',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='circuitparamboost',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='circuitparambuck',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='circuitparambuck',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='circuitparamcuksepic',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='circuitparamcuksepic',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='circuitparamhalffullpush',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='circuitparamhalffullpush',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='devicescategories',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='devicescategories',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='devicethermalinfo',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='devicethermalinfo',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='elitpowertool.devicescategories'),
        ),
        migrations.AddField(
            model_name='order',
            name='circuit_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='order',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='device_thermal_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elitpowertool.devicethermalinfo'),
        ),
        migrations.AddField(
            model_name='order',
            name='mosfet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mosfet.mosfetdata'),
        ),
        migrations.AddField(
            model_name='order',
            name='mosfet_raw',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mosfet.mosfetrawdata'),
        ),
        migrations.AddField(
            model_name='order',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='unitsmodel',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='unitsmodel',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='devicethermalinfo',
            name='resistance_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_resistances_unit', to='elitpowertool.unitsmodel'),
        ),
        migrations.AddField(
            model_name='devicethermalinfo',
            name='thermal_resistance_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_thermal_resistance_unit', to='elitpowertool.unitsmodel'),
        ),
        migrations.AddField(
            model_name='circuitparamhalffullpush',
            name='leakage_inductor_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_inductor_unit', to='elitpowertool.unitsmodel'),
        ),
        migrations.AddField(
            model_name='circuitparamflybackforword',
            name='magnetising_inductor_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_inductor_unit', to='elitpowertool.unitsmodel'),
        ),
        migrations.AddField(
            model_name='circuitparamflybackforword',
            name='mode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_mode', to='elitpowertool.unitsmodel'),
        ),
        migrations.AddField(
            model_name='circuitparamflybackforword',
            name='output_capacitor_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_capacitor_unit', to='elitpowertool.unitsmodel'),
        ),
        migrations.AddField(
            model_name='circuitparamcuksepic',
            name='inductor_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_inductor_unit', to='elitpowertool.unitsmodel'),
        ),
        migrations.AddField(
            model_name='circuitparamcuksepic',
            name='mode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_mode', to='elitpowertool.unitsmodel'),
        ),
        migrations.AddField(
            model_name='circuitparamcuksepic',
            name='output_capacitor_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_capacitor_unit', to='elitpowertool.unitsmodel'),
        ),
        migrations.AddField(
            model_name='circuitparambuck',
            name='capacitor_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_capacitor_unit', to='elitpowertool.unitsmodel'),
        ),
        migrations.AddField(
            model_name='circuitparambuck',
            name='inductor_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_inductor_unit', to='elitpowertool.unitsmodel'),
        ),
        migrations.AddField(
            model_name='circuitparambuck',
            name='mode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_mode', to='elitpowertool.unitsmodel'),
        ),
        migrations.AddField(
            model_name='circuitparamboost',
            name='capacitor_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_capacitor_unit', to='elitpowertool.unitsmodel'),
        ),
        migrations.AddField(
            model_name='circuitparamboost',
            name='inductor_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_inductor_unit', to='elitpowertool.unitsmodel'),
        ),
        migrations.AddField(
            model_name='circuitparamboost',
            name='mode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_mode', to='elitpowertool.unitsmodel'),
        ),
        migrations.AddField(
            model_name='circuitparamacdc',
            name='dead_time_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_time_unit', to='elitpowertool.unitsmodel'),
        ),
        migrations.AddField(
            model_name='circuitparamacdc',
            name='gird_frequency_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_frequency_unit', to='elitpowertool.unitsmodel'),
        ),
        migrations.AddField(
            model_name='circuitparamacdc',
            name='grid_inductance_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_inductance_unit', to='elitpowertool.unitsmodel'),
        ),
        migrations.AddField(
            model_name='circuitparamacdc',
            name='mode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_mode_acdc_unit', to='elitpowertool.unitsmodel'),
        ),
        migrations.AddField(
            model_name='voltagepower',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='voltagepower',
            name='gate_voltage_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='gate_voltage_unit', to='elitpowertool.unitsmodel'),
        ),
        migrations.AddField(
            model_name='voltagepower',
            name='output_power_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='power_unit', to='elitpowertool.unitsmodel'),
        ),
        migrations.AddField(
            model_name='voltagepower',
            name='output_voltage_current_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='voltage_current_unit', to='elitpowertool.unitsmodel'),
        ),
        migrations.AddField(
            model_name='voltagepower',
            name='switching_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='switch_unit', to='elitpowertool.unitsmodel'),
        ),
        migrations.AddField(
            model_name='voltagepower',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='voltage_power',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elitpowertool.voltagepower'),
        ),
        migrations.CreateModel(
            name='CircuitParamActiveFlybackForword',
            fields=[
                ('circuitparamflybackforword_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='elitpowertool.circuitparamflybackforword')),
                ('dead_time', models.FloatField(validators=[django.core.validators.MaxValueValidator(100000.0)])),
                ('dead_time_unit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_time_unit', to='elitpowertool.unitsmodel')),
            ],
            options={
                'db_table': 'cp_active_ff',
            },
            bases=('elitpowertool.circuitparamflybackforword',),
        ),
    ]
