# Generated by Django 5.0 on 2024-02-27 04:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elitpowertool', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicescategories',
            name='image_url',
            field=models.FileField(max_length=256, upload_to='devicesCategories/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'svg', 'gif', 'tiff', 'tif', 'bmp', 'svg', 'webp', 'ico', 'psd', 'raw'])]),
        ),
    ]
