# Generated by Django 5.0 on 2024-02-15 07:05

import utility.field
import utility.malicious_validator
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('blog_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('blog_title', models.CharField(max_length=256, validators=[utility.malicious_validator.validate_no_malicious_content])),
                ('blog_description', models.TextField(max_length=65536)),
                ('blog_image', models.ImageField(upload_to='blogs/')),
                ('seo_description', models.CharField(blank=True, max_length=256, null=True, validators=[utility.malicious_validator.validate_no_malicious_content])),
                ('blog_url', models.CharField(max_length=512, validators=[utility.malicious_validator.validate_no_malicious_content])),
                ('status', models.CharField(choices=[('draft', 'draft'), ('saved', 'saved'), ('published', 'published'), ('unpublished', 'unpublished')], max_length=16)),
                ('created_at', utility.field.UnixTimestampField(null=True)),
                ('updated_at', utility.field.UnixTimestampField(null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'blog',
                'ordering': ['blog_id', 'blog_title', 'blog_url', 'seo_description', 'blog_description', 'blog_image', 'status', 'created_by', 'updated_by', 'created_at', 'updated_at', 'is_active'],
            },
        ),
    ]
