# Generated by Django 5.0 on 2024-02-15 07:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('elitpowertool', '0001_initial'),
        ('mosfet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mosfetdata',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mosfetdata',
            name='final_resistance_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='final_resistance_unit', to='elitpowertool.unitsmodel'),
        ),
        migrations.AddField(
            model_name='mosfetdata',
            name='final_temp_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='final_temp_unit', to='elitpowertool.unitsmodel'),
        ),
        migrations.AddField(
            model_name='mosfetdata',
            name='power_loss_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='power_loss_unit', to='elitpowertool.unitsmodel'),
        ),
        migrations.AddField(
            model_name='mosfetdata',
            name='swoff_power_loss_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='swoff_power_loss_unit', to='elitpowertool.unitsmodel'),
        ),
        migrations.AddField(
            model_name='mosfetdata',
            name='swon_power_loss_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='swon_power_loss_unit', to='elitpowertool.unitsmodel'),
        ),
        migrations.AddField(
            model_name='mosfetdata',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mosfetrawdata',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mosfetrawdata',
            name='diode_forward_voltage_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='diode_forward_voltage_unit', to='elitpowertool.unitsmodel'),
        ),
        migrations.AddField(
            model_name='mosfetrawdata',
            name='gate_drain_charge_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='gate_drain_charge_unit', to='elitpowertool.unitsmodel'),
        ),
        migrations.AddField(
            model_name='mosfetrawdata',
            name='gate_plateau_voltage_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='gate_plateau_unit', to='elitpowertool.unitsmodel'),
        ),
        migrations.AddField(
            model_name='mosfetrawdata',
            name='gate_resistance_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='gate_resistance_unit', to='elitpowertool.unitsmodel'),
        ),
        migrations.AddField(
            model_name='mosfetrawdata',
            name='gate_threshold_voltage_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='gate_threshold_unit', to='elitpowertool.unitsmodel'),
        ),
        migrations.AddField(
            model_name='mosfetrawdata',
            name='input_capacitance_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='input_capacitance_unit', to='elitpowertool.unitsmodel'),
        ),
        migrations.AddField(
            model_name='mosfetrawdata',
            name='internal_gate_resistance_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='internal_gate_resistance_unit', to='elitpowertool.unitsmodel'),
        ),
        migrations.AddField(
            model_name='mosfetrawdata',
            name='reverse_recovery_charge_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='reverse_recovery_charge_unit', to='elitpowertool.unitsmodel'),
        ),
        migrations.AddField(
            model_name='mosfetrawdata',
            name='reverse_recovery_time_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='reverse_recovery_time_unit', to='elitpowertool.unitsmodel'),
        ),
        migrations.AddField(
            model_name='mosfetrawdata',
            name='reverse_trans_cap_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='reverse_trans_cap_unit', to='elitpowertool.unitsmodel'),
        ),
        migrations.AddField(
            model_name='mosfetrawdata',
            name='thermal_resistance_junction_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='thermal_resistance_junction_unit', to='elitpowertool.unitsmodel'),
        ),
        migrations.AddField(
            model_name='mosfetrawdata',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
