# Generated by Django 5.0 on 2024-02-19 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosfet', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mosfetrawdata',
            name='coordinates_data',
            field=models.TextField(max_length=1024),
        ),
    ]
